FROM python:3.10-slim

WORKDIR /app/model_training

COPY model_training/requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY model_training ./

CMD ["python", "find_similar.py"]
